variables:
  SPHINXBUILD: sphinx-build
  DOCSDIR: docs
  SOURCEDIR: source
  BUILDDIR: public
  BUILDFORMAT: html
  REPORT: report.xml
  COVERAGE: coverage.xml

stages:
  - test
  - build
  - deploy

image: python:3.12

before_script:
  - apt-get update
  - apt-get install -y git
  - python -m venv venv
  - source venv/bin/activate
  - python -m ensurepip --upgrade
  - pip install -r requirements.txt

tests:
  tags:
    - python
  stage: test
  script:
    - pip install pytest
    - pytest --junitxml=${REPORT}
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit: ${REPORT}

coverage:
  tags:
    - python
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --cov-report term --cov-report xml:${COVERAGE} --cov=src/ptdismap tests
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ${COVERAGE}

pages:
  tags:
    - python
  stage: build
  script:
    - pip install sphinx sphinx-rtd-theme
    - ${SPHINXBUILD} -b ${BUILDFORMAT} ${DOCSDIR}/${SOURCEDIR} ${BUILDDIR}
  artifacts:
    paths:
      - ${BUILDDIR}
  only:
    - main
