[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
authors = [
    { name = "Riccardo Finotello", email = "riccardo.finotello@cea.fr" },
    { name = "Parham Radpay", email = "parhamradpay@gmail.com" },
]
name = "frg-signal-detection"
description = "An agnostic definition of detection limit using renormalisation group techniques"
maintainers = [
    { name = "Riccardo Finotello", email = "riccardo.finotello@cea.fr" },
]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12,<3.13"
keywords = [
    "signal detection",
    "renormalisation group",
    "theoretical physics",
    "information theory",
    "field theory",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
]
license = { file = "LICENSE" }
dynamic = ["version"]
dependencies = [
    "imageio>=2.37.0",
    "ipykernel==6.29.5",
    "jaxtyping>=0.3.9",
    "matplotlib==3.9.2",
    "numpy==2.1.3",
    "pandas==2.3.0",
    "scikit-image==0.25.0",
    "scipy==1.14.1",
    "yacs==0.1.8",
]

[dependency-groups]
dev = ["better-exceptions>=0.3.3", "pre-commit>=4.2.0"]
docs = ["sphinx>=8.2.3", "sphinx-rtd-theme>=3.0.2"]
test = ["pytest>=8.4.1", "pytest-cov>=6.2.1"]

[project.optional-dependencies]
test = ["pytest>=8.4.1", "pytest-cov>=6.2.1"]
docs = ["sphinx>=8.2.3", "sphinx-rtd-theme>=3.0.2"]
dev = ["better-exceptions>=0.3.3", "pre-commit>=4.2.0"]

[project.urls]
Homepage = "https://github.com/thesfinox/frg-signal-detection"
Documentation = "https://frg-signal-detection.readthedocs.io/en/latest/"
Repository = "https://github.com/thesfinox/frg-signal-detection"
Issues = "https://github.com/thesfinox/frg-signal-detection/issues"

[project.scripts]
frg-canonical-dimensions = "frg.scripts.canonical_dimensions:cli"
frg-evc-distribution = "frg.scripts.evc_distribution:cli"
frg-equations = "frg.scripts.frg_equations:cli"
frg-equations-lpa = "frg.scripts.frg_equations_lpa:cli"
frg-generate-config = "frg.scripts.generate_config:cli"
frg-plot-canonical-dimensions = "frg.scripts.plot_canonical_dimensions:cli"
frg-plot-canonical-dimensions-scan = "frg.scripts.plot_canonical_dimensions_scan:cli"
frg-init = "frg.scripts.init:cli"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.wheel]
packages = ["src/frg"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".venv",
]

line-length = 80
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "C", "D", "DOC"]
ignore = ["D203", "D213", "D413", "D415"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
preview = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
preview = true

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
